package entidades;
// Generated 31-ago-2017 10:25:34 by Hibernate Tools 4.3.1



/**
 * Cancha generated by hbm2java
 */
public class Cancha  implements java.io.Serializable {


     private Integer idCancha;
     private String dimencionesCancha;
     private int idClub;
     private int idFecha;

    public Cancha() {
    }

    public Cancha(String dimencionesCancha, int idClub, int idFecha) {
       this.dimencionesCancha = dimencionesCancha;
       this.idClub = idClub;
       this.idFecha = idFecha;
    }
   
    public Integer getIdCancha() {
        return this.idCancha;
    }
    
    public void setIdCancha(Integer idCancha) {
        this.idCancha = idCancha;
    }
    public String getDimencionesCancha() {
        return this.dimencionesCancha;
    }
    
    public void setDimencionesCancha(String dimencionesCancha) {
        this.dimencionesCancha = dimencionesCancha;
    }
    public int getIdClub() {
        return this.idClub;
    }
    
    public void setIdClub(int idClub) {
        this.idClub = idClub;
    }
    public int getIdFecha() {
        return this.idFecha;
    }
    
    public void setIdFecha(int idFecha) {
        this.idFecha = idFecha;
    }




}


