package entidades;
// Generated 31-ago-2017 10:25:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nombreCliente;
     private Date fechaNacimientoCliente;
     private String telefonoCliente;
     private String EMailCliente;
     private int idUsuario;

    public Cliente() {
    }

    public Cliente(String nombreCliente, Date fechaNacimientoCliente, String telefonoCliente, String EMailCliente, int idUsuario) {
       this.nombreCliente = nombreCliente;
       this.fechaNacimientoCliente = fechaNacimientoCliente;
       this.telefonoCliente = telefonoCliente;
       this.EMailCliente = EMailCliente;
       this.idUsuario = idUsuario;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public Date getFechaNacimientoCliente() {
        return this.fechaNacimientoCliente;
    }
    
    public void setFechaNacimientoCliente(Date fechaNacimientoCliente) {
        this.fechaNacimientoCliente = fechaNacimientoCliente;
    }
    public String getTelefonoCliente() {
        return this.telefonoCliente;
    }
    
    public void setTelefonoCliente(String telefonoCliente) {
        this.telefonoCliente = telefonoCliente;
    }
    public String getEMailCliente() {
        return this.EMailCliente;
    }
    
    public void setEMailCliente(String EMailCliente) {
        this.EMailCliente = EMailCliente;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


