package entidades;
// Generated 31-ago-2017 10:25:34 by Hibernate Tools 4.3.1



/**
 * Club generated by hbm2java
 */
public class Club  implements java.io.Serializable {


     private Integer idClub;
     private String nombreClub;
     private String direccionChub;
     private String telefonoClub;
     private String administradorClub;
     private int idUsuario;

    public Club() {
    }

    public Club(String nombreClub, String direccionChub, String telefonoClub, String administradorClub, int idUsuario) {
       this.nombreClub = nombreClub;
       this.direccionChub = direccionChub;
       this.telefonoClub = telefonoClub;
       this.administradorClub = administradorClub;
       this.idUsuario = idUsuario;
    }
   
    public Integer getIdClub() {
        return this.idClub;
    }
    
    public void setIdClub(Integer idClub) {
        this.idClub = idClub;
    }
    public String getNombreClub() {
        return this.nombreClub;
    }
    
    public void setNombreClub(String nombreClub) {
        this.nombreClub = nombreClub;
    }
    public String getDireccionChub() {
        return this.direccionChub;
    }
    
    public void setDireccionChub(String direccionChub) {
        this.direccionChub = direccionChub;
    }
    public String getTelefonoClub() {
        return this.telefonoClub;
    }
    
    public void setTelefonoClub(String telefonoClub) {
        this.telefonoClub = telefonoClub;
    }
    public String getAdministradorClub() {
        return this.administradorClub;
    }
    
    public void setAdministradorClub(String administradorClub) {
        this.administradorClub = administradorClub;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


