package entidades;
// Generated 31-ago-2017 10:25:34 by Hibernate Tools 4.3.1



/**
 * Fecha generated by hbm2java
 */
public class Fecha  implements java.io.Serializable {


     private Integer idFecha;
     private int diaFecha;
     private int mesFecha;
     private int anoFecha;
     private int idHora;
     private boolean disponibleFecha;

    public Fecha() {
    }

    public Fecha(int diaFecha, int mesFecha, int anoFecha, int idHora, boolean disponibleFecha) {
       this.diaFecha = diaFecha;
       this.mesFecha = mesFecha;
       this.anoFecha = anoFecha;
       this.idHora = idHora;
       this.disponibleFecha = disponibleFecha;
    }
   
    public Integer getIdFecha() {
        return this.idFecha;
    }
    
    public void setIdFecha(Integer idFecha) {
        this.idFecha = idFecha;
    }
    public int getDiaFecha() {
        return this.diaFecha;
    }
    
    public void setDiaFecha(int diaFecha) {
        this.diaFecha = diaFecha;
    }
    public int getMesFecha() {
        return this.mesFecha;
    }
    
    public void setMesFecha(int mesFecha) {
        this.mesFecha = mesFecha;
    }
    public int getAnoFecha() {
        return this.anoFecha;
    }
    
    public void setAnoFecha(int anoFecha) {
        this.anoFecha = anoFecha;
    }
    public int getIdHora() {
        return this.idHora;
    }
    
    public void setIdHora(int idHora) {
        this.idHora = idHora;
    }
    public boolean isDisponibleFecha() {
        return this.disponibleFecha;
    }
    
    public void setDisponibleFecha(boolean disponibleFecha) {
        this.disponibleFecha = disponibleFecha;
    }




}


