package entidades;
// Generated 31-ago-2017 10:25:34 by Hibernate Tools 4.3.1



/**
 * Hora generated by hbm2java
 */
public class Hora  implements java.io.Serializable {


     private Integer idHora;
     private int horaHora;
     private boolean disponibleHora;

    public Hora() {
    }

    public Hora(int horaHora, boolean disponibleHora) {
       this.horaHora = horaHora;
       this.disponibleHora = disponibleHora;
    }
   
    public Integer getIdHora() {
        return this.idHora;
    }
    
    public void setIdHora(Integer idHora) {
        this.idHora = idHora;
    }
    public int getHoraHora() {
        return this.horaHora;
    }
    
    public void setHoraHora(int horaHora) {
        this.horaHora = horaHora;
    }
    public boolean isDisponibleHora() {
        return this.disponibleHora;
    }
    
    public void setDisponibleHora(boolean disponibleHora) {
        this.disponibleHora = disponibleHora;
    }




}


