package entidades;
// Generated 31-ago-2017 10:25:34 by Hibernate Tools 4.3.1



/**
 * Reservas generated by hbm2java
 */
public class Reservas  implements java.io.Serializable {


     private int idReservas;
     private int idCliente;
     private int idClub;
     private int idCancha;
     private int idFecha;

    public Reservas() {
    }

    public Reservas(int idReservas, int idCliente, int idClub, int idCancha, int idFecha) {
       this.idReservas = idReservas;
       this.idCliente = idCliente;
       this.idClub = idClub;
       this.idCancha = idCancha;
       this.idFecha = idFecha;
    }
   
    public int getIdReservas() {
        return this.idReservas;
    }
    
    public void setIdReservas(int idReservas) {
        this.idReservas = idReservas;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public int getIdClub() {
        return this.idClub;
    }
    
    public void setIdClub(int idClub) {
        this.idClub = idClub;
    }
    public int getIdCancha() {
        return this.idCancha;
    }
    
    public void setIdCancha(int idCancha) {
        this.idCancha = idCancha;
    }
    public int getIdFecha() {
        return this.idFecha;
    }
    
    public void setIdFecha(int idFecha) {
        this.idFecha = idFecha;
    }




}


