package entidades;
// Generated 31-ago-2017 10:25:34 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombreUsuario;
     private String EMailUsuario;
     private String contrasenaUsuario;
     private String tipoUsuario;

    public Usuarios() {
    }

    public Usuarios(String nombreUsuario, String EMailUsuario, String contrasenaUsuario, String tipoUsuario) {
       this.nombreUsuario = nombreUsuario;
       this.EMailUsuario = EMailUsuario;
       this.contrasenaUsuario = contrasenaUsuario;
       this.tipoUsuario = tipoUsuario;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getEMailUsuario() {
        return this.EMailUsuario;
    }
    
    public void setEMailUsuario(String EMailUsuario) {
        this.EMailUsuario = EMailUsuario;
    }
    public String getContrasenaUsuario() {
        return this.contrasenaUsuario;
    }
    
    public void setContrasenaUsuario(String contrasenaUsuario) {
        this.contrasenaUsuario = contrasenaUsuario;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }




}


